// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "swagger": "2.0",
  "info": {
    "title": "XenoChoice Sandbox API («Машина выбора»)",
    "version": "2.0.0",
    "description": "Авторитетный детерминированный движок симуляции небиологических сообществ на реальных планетах (Земля, Марс, Венера) в соответствии с ТЗ v2 и ТЗ v1.",
    "contact": {
      "name": "XenoChoice Team",
      "email": "support@xenochoice.io"
    },
    "license": {
      "name": "MIT"
    }
  },
  "basePath": "",
  "schemes": [
    "http",
    "https",
    "ws",
    "wss"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "tags": [
    {
      "name": "XenoChoice v2 - Worlds",
      "description": "Каталог планет и физических сред со справочными данными NASA"
    },
    {
      "name": "XenoChoice v2 - Experiments",
      "description": "Управление экспериментами, жизненный цикл симуляции, Replay, Preview и Compare"
    },
    {
      "name": "XenoChoice v2 - Interventions",
      "description": "Воздействия исследователя (импульс, буря, истощение, каналы, режим)"
    },
    {
      "name": "XenoChoice v2 - Inspection",
      "description": "Инспектор состояния колоний, трассировка решений особей и метрики"
    },
    {
      "name": "XenoChoice v2 - Import/Export",
      "description": "Экспорт в JSON/CSV и асинхронный импорт экспериментов"
    },
    {
      "name": "XenoChoice v2 - Streaming",
      "description": "WebSocket стриминг телеметрии и кадров симуляции в реальном времени"
    },
    {
      "name": "System",
      "description": "Системные эндпоинты: Healthcheck, Readiness и Prometheus метрики"
    },
    {
      "name": "XenoChoice v1 - Legacy API",
      "description": "API v1: колонии, распределение ресурсов и чат-хаб"
    }
  ],
  "paths": {
    "/health": {
      "get": {
        "tags": [
          "System"
        ],
        "summary": "Healthcheck сервиса",
        "description": "Возвращает статус работоспособности HTTP-сервера",
        "responses": {
          "200": {
            "description": "Сервис работает",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "ok"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/ready": {
      "get": {
        "tags": [
          "System"
        ],
        "summary": "Readiness-проверка сервиса",
        "description": "Проверяет доступность базы данных PostgreSQL и Redis",
        "responses": {
          "200": {
            "description": "Все зависимости доступны",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "ready"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Одна из зависимостей недоступна",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/metrics": {
      "get": {
        "tags": [
          "System"
        ],
        "summary": "Prometheus метрики",
        "description": "Экспортирует системные и прикладные метрики (RPS, latency, in-flight) в формате Prometheus",
        "produces": [
          "text/plain"
        ],
        "responses": {
          "200": {
            "description": "Текстовый поток метрик Prometheus"
          }
        }
      }
    },
    "/api/v2/worlds": {
      "get": {
        "tags": [
          "XenoChoice v2 - Worlds"
        ],
        "summary": "Получить список доступных планет со справочными данными NASA",
        "description": "Возвращает Землю, Марс и Венеру с реальными справочными параметрами (NASA Planetary Fact Sheet), локальными сценариями и параметрами абстрактного организма.",
        "responses": {
          "200": {
            "description": "Список миров",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/World"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/experiments": {
      "get": {
        "tags": [
          "XenoChoice v2 - Experiments"
        ],
        "summary": "Список всех активных экспериментов в памяти",
        "responses": {
          "200": {
            "description": "Список экспериментов",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/Experiment"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "XenoChoice v2 - Experiments"
        ],
        "summary": "Создать новый эксперимент на выбранной планете",
        "description": "Инициализирует мир, две первичные колонии по 6 особей, каналы связей и детерминированный PRNG SplitMix64 с заданным seed.",
        "parameters": [
          {
            "name": "request",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateExperimentRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Эксперимент создан",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "$ref": "#/definitions/Experiment"
                }
              }
            }
          },
          "400": {
            "description": "Некорректные параметры",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/api/v2/experiments/{id}": {
      "get": {
        "tags": [
          "XenoChoice v2 - Experiments"
        ],
        "summary": "Получить детальную информацию об эксперименте по ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "example": "exp-a1b2c3d4"
          }
        ],
        "responses": {
          "200": {
            "description": "Эксперимент найден",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "$ref": "#/definitions/Experiment"
                }
              }
            }
          },
          "404": {
            "description": "Эксперимент не найден",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "XenoChoice v2 - Experiments"
        ],
        "summary": "Удалить эксперимент",
        "description": "Останавливает симуляцию и освобождает ресурсы",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "example": "exp-a1b2c3d4"
          }
        ],
        "responses": {
          "200": {
            "description": "Успешно удалено",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                }
              }
            }
          },
          "404": {
            "description": "Эксперимент не найден",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/api/v2/experiments/{id}/state": {
      "get": {
        "tags": [
          "XenoChoice v2 - Experiments"
        ],
        "summary": "Получить текущий полный авторитетный снимок (StateSnapshot)",
        "description": "Возвращает канонический снимок мира, всех живых особей, колоний, каналов связи, пакетов в пути, метрик и баланса энергии.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "example": "exp-a1b2c3d4"
          }
        ],
        "responses": {
          "200": {
            "description": "Авторитетный снимок состояния",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "$ref": "#/definitions/StateSnapshot"
                }
              }
            }
          },
          "404": {
            "description": "Эксперимент не найден",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/api/v2/experiments/{id}/commands": {
      "post": {
        "tags": [
          "XenoChoice v2 - Experiments"
        ],
        "summary": "Управление жизненным циклом (start, pause, step, reset, speed)",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "example": "exp-a1b2c3d4"
          },
          {
            "name": "command",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CommandRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Команда выполнена",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "running"
                    },
                    "speed": {
                      "type": "integer",
                      "example": 1
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Некорректная команда",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/api/v2/experiments/{id}/interventions": {
      "post": {
        "tags": [
          "XenoChoice v2 - Interventions"
        ],
        "summary": "Применить внешнее воздействие исследователя",
        "description": "Добавляет в журнал детерминированное воздействие: impulse (энергетический всплеск), perturbation (буря/шум), depletion (истощение ресурса), set_channel (изменение связи), set_mode, set_flow, set_noise.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "example": "exp-a1b2c3d4"
          },
          {
            "name": "intervention",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/InterventionRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Воздействие зарегистрировано в журнале",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "$ref": "#/definitions/Intervention"
                }
              }
            }
          },
          "400": {
            "description": "Ошибка в параметрах воздействия",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/api/v2/experiments/{id}/preview": {
      "get": {
        "tags": [
          "XenoChoice v2 - Experiments"
        ],
        "summary": "Предпросмотр снимка состояния на произвольном такте (Preview)",
        "description": "Воспроизводит симуляцию во временном контексте до указанного такта без перемотки основного эксперимента.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "example": "exp-a1b2c3d4"
          },
          {
            "name": "tick",
            "in": "query",
            "required": true,
            "type": "integer",
            "example": 150
          }
        ],
        "responses": {
          "200": {
            "description": "Снимок на запрошенном такте",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "$ref": "#/definitions/StateSnapshot"
                }
              }
            }
          },
          "400": {
            "description": "Некорректный такт",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/api/v2/experiments/{id}/compare": {
      "get": {
        "tags": [
          "XenoChoice v2 - Experiments"
        ],
        "summary": "Сравнить три режима (реактивный, адаптивный, эволюционный)",
        "description": "Запускает параллельное сопоставление трёх режимов принятия решений на одинаковом seed и условиях для причинно-следственного анализа (Causal Inference).",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "example": "exp-a1b2c3d4"
          },
          {
            "name": "ticks",
            "in": "query",
            "required": false,
            "type": "integer",
            "default": 300,
            "example": 300
          }
        ],
        "responses": {
          "200": {
            "description": "Результаты сравнения по трем режимам",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/CompareResult"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/experiments/{id}/colonies/{colonyId}": {
      "get": {
        "tags": [
          "XenoChoice v2 - Inspection"
        ],
        "summary": "Получить состояние колонии и агрегированные метрики",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "colonyId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Данные колонии",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "$ref": "#/definitions/Colony"
                }
              }
            }
          },
          "404": {
            "description": "Колония не найдена",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/api/v2/experiments/{id}/individuals/{individualId}": {
      "get": {
        "tags": [
          "XenoChoice v2 - Inspection"
        ],
        "summary": "Инспектор особи: энергия, структура, динамическая память и трассировка решения",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "individualId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Полные характеристики особи",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "$ref": "#/definitions/Individual"
                }
              }
            }
          },
          "404": {
            "description": "Особь не найдена",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/api/v2/experiments/{id}/metrics": {
      "get": {
        "tags": [
          "XenoChoice v2 - Inspection"
        ],
        "summary": "История метрик эксперимента по тактам",
        "description": "Возвращает временной ряд показателей: полезная мощность, энтропия решений, энергоэффективность, невязка баланса.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Временной ряд метрик",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/MetricsSnapshot"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/experiments/{id}/export": {
      "get": {
        "tags": [
          "XenoChoice v2 - Import/Export"
        ],
        "summary": "Экспорт результатов эксперимента в JSON или CSV",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "format",
            "in": "query",
            "type": "string",
            "enum": [
              "json",
              "csv"
            ],
            "default": "json"
          }
        ],
        "responses": {
          "200": {
            "description": "Файл экспорта JSON или CSV"
          }
        }
      }
    },
    "/api/v2/experiments/import": {
      "post": {
        "tags": [
          "XenoChoice v2 - Import/Export"
        ],
        "summary": "Асинхронный импорт JSON-бандла эксперимента",
        "description": "Запускает фоновую валидацию и воспроизведение (Replay) импортированной записи с проверкой контрольной суммы.",
        "parameters": [
          {
            "name": "bundle",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ExportBundle"
            }
          }
        ],
        "responses": {
          "202": {
            "description": "Задание на импорт принято в обработку",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "$ref": "#/definitions/ImportProgress"
                }
              }
            }
          },
          "400": {
            "description": "Некорректный JSON-бандл",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/api/v2/imports/{id}": {
      "get": {
        "tags": [
          "XenoChoice v2 - Import/Export"
        ],
        "summary": "Получить статус и прогресс задания импорта",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "example": "job-uuid"
          }
        ],
        "responses": {
          "200": {
            "description": "Текущий прогресс импорта",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "$ref": "#/definitions/ImportProgress"
                }
              }
            }
          },
          "404": {
            "description": "Задание не найдено",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "XenoChoice v2 - Import/Export"
        ],
        "summary": "Отменить фоновое задание импорта",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "example": "job-uuid"
          }
        ],
        "responses": {
          "200": {
            "description": "Задание отменено",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "$ref": "#/definitions/ImportProgress"
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/experiments/{id}/replay": {
      "post": {
        "tags": [
          "XenoChoice v2 - Experiments"
        ],
        "summary": "Воспроизвести эксперимент от такта 0 до targetTick (Replay)",
        "description": "Запускает детерминированное повторение от начального состояния с тем же seed и вмешательствами, проверяя контрольную сумму SHA-256.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "replay",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ReplayRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Результат воспроизведения",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "$ref": "#/definitions/StateSnapshot"
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/experiments/{id}/stream": {
      "get": {
        "tags": [
          "XenoChoice v2 - Streaming"
        ],
        "summary": "WebSocket стриминг состояния мира в реальном времени (до 50 Гц)",
        "description": "Двунаправленное постоянное соединение. Сервер непрерывно передает StateSnapshot, клиент может посылать команды.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "101": {
            "description": "Переключение протокола на WebSocket (Switching Protocols)"
          }
        }
      }
    },
    "/api/v1/colonies": {
      "get": {
        "tags": [
          "XenoChoice v1 - Legacy API"
        ],
        "summary": "Список всех колоний (v1)",
        "responses": {
          "200": {
            "description": "Список колоний v1",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ColonyV1"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/colonies/{id}": {
      "get": {
        "tags": [
          "XenoChoice v1 - Legacy API"
        ],
        "summary": "Получить колонию по ID (v1)",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Колония v1",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "$ref": "#/definitions/ColonyV1"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/environment": {
      "get": {
        "tags": [
          "XenoChoice v1 - Legacy API"
        ],
        "summary": "Состояние среды (v1)",
        "responses": {
          "200": {
            "description": "Параметры среды v1",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "$ref": "#/definitions/EnvironmentV1"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/environment/trigger": {
      "post": {
        "tags": [
          "XenoChoice v1 - Legacy API"
        ],
        "summary": "Триггер события среды (v1)",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "event": {
                  "type": "string",
                  "example": "solar_flare"
                },
                "intensity": {
                  "type": "number",
                  "example": 1.5
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Событие применено"
          }
        }
      }
    },
    "/api/v1/simulation/step": {
      "post": {
        "tags": [
          "XenoChoice v1 - Legacy API"
        ],
        "summary": "Сделать один шаг симуляции (v1)",
        "responses": {
          "200": {
            "description": "Шаг выполнен"
          }
        }
      }
    },
    "/api/v1/simulation/reset": {
      "post": {
        "tags": [
          "XenoChoice v1 - Legacy API"
        ],
        "summary": "Сбросить симуляцию (v1)",
        "responses": {
          "200": {
            "description": "Симуляция сброшена"
          }
        }
      }
    },
    "/api/v1/choice/allocate": {
      "post": {
        "tags": [
          "XenoChoice v1 - Legacy API"
        ],
        "summary": "Аллокация ресурсов между колониями (v1)",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "sourceId": {
                  "type": "string",
                  "example": "col-1"
                },
                "targetId": {
                  "type": "string",
                  "example": "col-2"
                },
                "amount": {
                  "type": "number",
                  "example": 15.0
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ресурсы перераспределены"
          }
        }
      }
    },
    "/api/v1/choice/dilemmas": {
      "get": {
        "tags": [
          "XenoChoice v1 - Legacy API"
        ],
        "summary": "Список этических и ресурсных дилемм (v1)",
        "responses": {
          "200": {
            "description": "Список дилемм",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": true
                },
                "data": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string",
                        "example": "dil-1"
                      },
                      "title": {
                        "type": "string",
                        "example": "Энергетический кризис"
                      },
                      "description": {
                        "type": "string",
                        "example": "Поделиться ли резервом с угасающей колонией?"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/choice/dilemmas/resolve": {
      "post": {
        "tags": [
          "XenoChoice v1 - Legacy API"
        ],
        "summary": "Разрешить дилемму (v1)",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "dilemmaId": {
                  "type": "string",
                  "example": "dil-1"
                },
                "choice": {
                  "type": "string",
                  "example": "share"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Решение принято"
          }
        }
      }
    },
    "/api/v1/ws": {
      "get": {
        "tags": [
          "XenoChoice v1 - Legacy API"
        ],
        "summary": "WebSocket хаб телеметрии и чата (v1)",
        "responses": {
          "101": {
            "description": "Switching Protocols to WebSocket"
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean",
          "example": false
        },
        "error": {
          "type": "object",
          "properties": {
            "code": {
              "type": "string",
              "example": "NOT_FOUND"
            },
            "message": {
              "type": "string",
              "example": "Experiment not found"
            }
          }
        }
      }
    },
    "World": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "example": "earth"
        },
        "name": {
          "type": "string",
          "example": "Земля"
        },
        "description": {
          "type": "string",
          "example": "Минеральная емкостная среда с электрическим градиентом"
        },
        "radius": {
          "type": "number",
          "example": 6371.0
        },
        "gravity": {
          "type": "number",
          "example": 9.81
        },
        "surfacePressure": {
          "type": "number",
          "example": 1.0
        },
        "meanTemperature": {
          "type": "number",
          "example": 288.0
        },
        "model": {
          "type": "object",
          "properties": {
            "energyType": {
              "type": "string",
              "example": "Электрический потенциал"
            },
            "sourceDescription": {
              "type": "string",
              "example": "Пьезо- и трибоэлектрические минеральные жилы"
            },
            "baseFlow": {
              "type": "number",
              "example": 10.0
            },
            "baseNoise": {
              "type": "number",
              "example": 0.1
            },
            "eMax": {
              "type": "number",
              "example": 100.0
            },
            "reserveTarget": {
              "type": "number",
              "example": 10.0
            }
          }
        }
      }
    },
    "CreateExperimentRequest": {
      "type": "object",
      "required": [
        "worldId",
        "seed"
      ],
      "properties": {
        "name": {
          "type": "string",
          "example": "Лаборатория Земля"
        },
        "worldId": {
          "type": "string",
          "example": "earth"
        },
        "mode": {
          "type": "string",
          "enum": [
            "reactive",
            "adaptive",
            "evolutionary"
          ],
          "example": "evolutionary"
        },
        "seed": {
          "type": "integer",
          "example": 2048
        }
      }
    },
    "Experiment": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "example": "exp-a1b2c3d4"
        },
        "name": {
          "type": "string",
          "example": "Лаборатория Земля"
        },
        "worldId": {
          "type": "string",
          "example": "earth"
        },
        "mode": {
          "type": "string",
          "example": "evolutionary"
        },
        "status": {
          "type": "string",
          "example": "running"
        },
        "seed": {
          "type": "integer",
          "example": 2048
        },
        "speed": {
          "type": "integer",
          "example": 1
        },
        "latestSnapshot": {
          "$ref": "#/definitions/StateSnapshot"
        },
        "createdAt": {
          "type": "string",
          "example": "2026-09-20T10:00:00Z"
        }
      }
    },
    "Genome": {
      "type": "object",
      "properties": {
        "wE": {
          "type": "number",
          "description": "Вес энергетической безопасности особи",
          "example": 0.3
        },
        "wD": {
          "type": "number",
          "description": "Штраф за риск дефицита",
          "example": 0.25
        },
        "wC": {
          "type": "number",
          "description": "Вес кооперации/помощи соседям",
          "example": 0.2
        },
        "wR": {
          "type": "number",
          "description": "Вес воспроизводства/деления",
          "example": 0.15
        },
        "wCost": {
          "type": "number",
          "description": "Штраф за необратимые затраты",
          "example": 0.1
        },
        "lambda": {
          "type": "number",
          "description": "Коэффициент сохранения памяти M",
          "example": 0.8
        },
        "hThreshold": {
          "type": "number",
          "description": "Порог переключения действия h",
          "example": 0.005
        }
      }
    },
    "Individual": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "example": "ind-0019"
        },
        "colonyId": {
          "type": "string",
          "example": "col-01"
        },
        "parentId": {
          "type": "string",
          "example": "ind-06"
        },
        "lat": {
          "type": "number",
          "example": 45.2
        },
        "lng": {
          "type": "number",
          "example": 12.8
        },
        "energy": {
          "type": "number",
          "example": 8.93
        },
        "biomass": {
          "type": "number",
          "example": 20.0
        },
        "memory": {
          "type": "number",
          "example": -0.003
        },
        "alive": {
          "type": "boolean",
          "example": true
        },
        "generation": {
          "type": "integer",
          "example": 2
        },
        "genome": {
          "$ref": "#/definitions/Genome"
        },
        "lastDecision": {
          "$ref": "#/definitions/DecisionTrace"
        }
      }
    },
    "DecisionTrace": {
      "type": "object",
      "properties": {
        "individualId": {
          "type": "string",
          "example": "ind-0019"
        },
        "tick": {
          "type": "integer",
          "example": 414
        },
        "selectedAction": {
          "type": "string",
          "enum": [
            "STORE",
            "TRANSFER",
            "GROW",
            "DIVIDE"
          ],
          "example": "STORE"
        },
        "selectedTarget": {
          "type": "string",
          "example": "ind-10"
        },
        "chosenScore": {
          "type": "number",
          "example": 0.2682
        },
        "reasoning": {
          "type": "string",
          "example": "Сохранение ресурса: ни одна альтернатива не превзошла порог h"
        },
        "scores": {
          "type": "object",
          "properties": {
            "STORE": {
              "type": "number",
              "example": 0.2682
            },
            "TRANSFER": {
              "type": "number",
              "example": 0.2655
            },
            "GROW": {
              "type": "number",
              "example": -1.0
            },
            "DIVIDE": {
              "type": "number",
              "example": -1.0
            }
          }
        }
      }
    },
    "Colony": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "example": "col-01"
        },
        "name": {
          "type": "string",
          "example": "Северное Сообщество"
        },
        "color": {
          "type": "string",
          "example": "#3b82f6"
        },
        "individualIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "metrics": {
          "type": "object",
          "properties": {
            "population": {
              "type": "integer",
              "example": 12
            },
            "totalEnergy": {
              "type": "number",
              "example": 115.03
            },
            "totalBiomass": {
              "type": "number",
              "example": 240.48
            }
          }
        }
      }
    },
    "Channel": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "example": "ch-01-02"
        },
        "fromId": {
          "type": "string",
          "example": "ind-0013"
        },
        "toId": {
          "type": "string",
          "example": "ind-0041"
        },
        "distance": {
          "type": "number",
          "example": 0.15
        },
        "maxPower": {
          "type": "number",
          "example": 2.0
        },
        "loss": {
          "type": "number",
          "example": 0.0762
        },
        "delayTicks": {
          "type": "integer",
          "example": 1
        },
        "enabled": {
          "type": "boolean",
          "example": true
        }
      }
    },
    "ResourcePacket": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "example": "pkt-1"
        },
        "senderId": {
          "type": "string",
          "example": "ind-0013"
        },
        "receiverId": {
          "type": "string",
          "example": "ind-0041"
        },
        "sentEnergy": {
          "type": "number",
          "example": 0.2
        },
        "netEnergy": {
          "type": "number",
          "example": 0.185
        },
        "lossEnergy": {
          "type": "number",
          "example": 0.015
        },
        "deliveryTick": {
          "type": "integer",
          "example": 415
        }
      }
    },
    "EnergyBalance": {
      "type": "object",
      "properties": {
        "initialStored": {
          "type": "number",
          "example": 480.0
        },
        "inoculated": {
          "type": "number",
          "example": 0.0
        },
        "externalInput": {
          "type": "number",
          "example": 1240.5
        },
        "currentStored": {
          "type": "number",
          "example": 890.2
        },
        "inTransit": {
          "type": "number",
          "example": 1.2
        },
        "maintenance": {
          "type": "number",
          "example": 620.4
        },
        "channelLoss": {
          "type": "number",
          "example": 45.1
        },
        "conversionLoss": {
          "type": "number",
          "example": 32.0
        },
        "divisionCost": {
          "type": "number",
          "example": 18.0
        },
        "deathDissipation": {
          "type": "number",
          "example": 113.6
        }
      }
    },
    "MetricsSnapshot": {
      "type": "object",
      "properties": {
        "tick": {
          "type": "integer",
          "example": 656
        },
        "population": {
          "type": "integer",
          "example": 28
        },
        "activeColonies": {
          "type": "integer",
          "example": 3
        },
        "usefulPower": {
          "type": "number",
          "example": 123.241
        },
        "efficiency": {
          "type": "number",
          "example": 84.5
        },
        "decisionEntropy": {
          "type": "number",
          "example": 1.28
        },
        "deliveryLatency": {
          "type": "number",
          "example": 1.4
        },
        "meanWelfare": {
          "type": "number",
          "example": 88.4
        },
        "balanceResidual": {
          "type": "number",
          "example": 4.55e-12
        }
      }
    },
    "StateSnapshot": {
      "type": "object",
      "properties": {
        "tick": {
          "type": "integer",
          "example": 656
        },
        "revision": {
          "type": "integer",
          "example": 656
        },
        "checksum": {
          "type": "string",
          "example": "a3b84f29c0d1e..."
        },
        "mode": {
          "type": "string",
          "example": "evolutionary"
        },
        "world": {
          "$ref": "#/definitions/World"
        },
        "individuals": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Individual"
          }
        },
        "colonies": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Colony"
          }
        },
        "channels": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Channel"
          }
        },
        "inTransit": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResourcePacket"
          }
        },
        "metrics": {
          "$ref": "#/definitions/MetricsSnapshot"
        },
        "balance": {
          "$ref": "#/definitions/EnergyBalance"
        }
      }
    },
    "CommandRequest": {
      "type": "object",
      "required": [
        "command"
      ],
      "properties": {
        "command": {
          "type": "string",
          "enum": [
            "start",
            "pause",
            "step",
            "reset",
            "speed"
          ],
          "example": "start"
        },
        "speed": {
          "type": "integer",
          "enum": [
            1,
            2,
            5
          ],
          "example": 1
        }
      }
    },
    "InterventionRequest": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "impulse",
            "perturbation",
            "depletion",
            "set_channel",
            "set_mode",
            "set_flow",
            "set_noise",
            "toggle_mutations",
            "add_inoculum"
          ],
          "example": "impulse"
        },
        "targetId": {
          "type": "string",
          "example": "world"
        },
        "value": {
          "type": "number",
          "example": 2.5
        },
        "duration": {
          "type": "integer",
          "example": 60
        }
      }
    },
    "Intervention": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "example": "event-123"
        },
        "tick": {
          "type": "integer",
          "example": 450
        },
        "sequence": {
          "type": "integer",
          "example": 1
        },
        "type": {
          "type": "string",
          "example": "impulse"
        },
        "targetId": {
          "type": "string",
          "example": "world"
        },
        "value": {
          "type": "number",
          "example": 2.5
        }
      }
    },
    "ReplayRequest": {
      "type": "object",
      "required": [
        "targetTick"
      ],
      "properties": {
        "targetTick": {
          "type": "integer",
          "example": 500
        }
      }
    },
    "CompareResult": {
      "type": "object",
      "properties": {
        "mode": {
          "type": "string",
          "example": "adaptive"
        },
        "metrics": {
          "$ref": "#/definitions/MetricsSnapshot"
        },
        "history": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/MetricsSnapshot"
          }
        }
      }
    },
    "ImportProgress": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "example": "job-uuid"
        },
        "status": {
          "type": "string",
          "enum": [
            "running",
            "completed",
            "failed",
            "cancelled"
          ],
          "example": "running"
        },
        "tick": {
          "type": "integer",
          "example": 350
        },
        "total": {
          "type": "integer",
          "example": 1000
        },
        "experimentId": {
          "type": "string",
          "example": "exp-a1b2c3d4"
        },
        "error": {
          "type": "string",
          "example": ""
        }
      }
    },
    "ExportBundle": {
      "type": "object",
      "required": [
        "schemaVersion",
        "seed",
        "world",
        "finalSnapshot"
      ],
      "properties": {
        "schemaVersion": {
          "type": "string",
          "example": "3.0.0"
        },
        "modelVersion": {
          "type": "string",
          "example": "surface-ecology-3.0"
        },
        "seed": {
          "type": "string",
          "example": "2048"
        },
        "world": {
          "$ref": "#/definitions/World"
        },
        "finalSnapshot": {
          "$ref": "#/definitions/StateSnapshot"
        }
      }
    },
    "ColonyV1": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "example": "colony-1"
        },
        "name": {
          "type": "string",
          "example": "Alpha"
        },
        "population": {
          "type": "integer",
          "example": 50
        },
        "energy": {
          "type": "number",
          "example": 245.0
        }
      }
    },
    "EnvironmentV1": {
      "type": "object",
      "properties": {
        "temperature": {
          "type": "number",
          "example": 295.0
        },
        "radiation": {
          "type": "number",
          "example": 0.05
        },
        "resources": {
          "type": "number",
          "example": 1000.0
        }
      }
    }
  }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"http", "https", "ws", "wss"},
	Title:            "XenoChoice Sandbox API («Машина выбора»)",
	Description:      "Авторитетный детерминированный движок симуляции небиологических сообществ на реальных планетах (Земля, Марс, Венера) по ТЗ v2 и ТЗ v1",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
